export const SET_USUARIO_ERROR = 'SET_USUARIO_ERROR';
export const SET_USUARIO_SUCCESS = 'SET_USUARIO_SUCCESS';

export const GET_CHARACTERS_ERROR = 'GET_CHARACTERS_ERROR';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const GET_CHARACTER_OK = 'GET_CHARACTER_OK';

export const POST_FORM = 'POST_FORM';
export const POST_FORM_SUCCESS = 'POST_FORM_SUCCESS';
export const POST_FORM_ERROR = 'POST_FORM_ERROR';

export const SET_COLOR = 'SET_COLOR';
export const SET_WIDTH = 'SET_WIDTH';

export const SET_LOADING = 'SET_LOADING';

export const GUARDAR_USER_DATA = 'GUARDAR_USER_DATA';
